# Generated by Django 4.1.7 on 2023-05-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
